# Abba Caving Plugin by lennartVH01

# Game duration in seconds
Duration: 1800

# Max players per game, users with permission AbbaCaving.joinFull can still join
PlayerCap: 10

# Points awarded for each item at the end of an Abba Match
ItemValues:
- IRON_ORE=1
- REDSTONE_ORE=2
- GOLD_ORE=4
- LAPIS_ORE=8
- DIAMOND_ORE=10
- EMERALD_ORE=10
- DIAMOND_BARDING=10
- GOLDEN_APPLE(1)=10

# Enables the contraband scanner
ScanContraband: true

# Prohibited items, automatically includes entries in ItemValues
Contraband:
- GOLDEN_APPLE(0)
- POTION

# Enables debugging
# ONLY USE IF YOU KNOW WHAT YOU ARE DOING OR HAVE BEEN ASKED TO DO SO BY A DEVELOPER
Debug: false