# Abba Caving Plugin by VonTum (https://github.com/VonTum)

# Game duration in seconds
Duration: 1800

# Max players per game, users with permission AbbaCaving.joinFull can still join
PlayerCap: 10

# Denotes the redistribution of ores after the game by score. 
Redistribution:
  Enabled: true
  # Weight of ores to be allotted to the leaderboard players
  Top:
  - 7
  - 2
  # Share of the ores to be allotted to the other players
  Other: 1
  OthersShare: false
# Example for 10 players
# If OthersShare == true then the first player would receive 70% of winnings, second would receive 20% and the remaining 10% is divided among the 8 remaining players
# If OthersShare == false then the first player would receive 7/(7+2+8*1)=7/17 of total winnings, second would receive 2/17 and every remaining player will get 1/17


# Points awarded for each item at the end of an Abba Match
# BlockData value can be added in () at the end of the type name
ItemValues:
- IRON_ORE=1
- REDSTONE_ORE=2
- GOLD_ORE=4
- LAPIS_ORE=8
- DIAMOND_ORE=10
- EMERALD_ORE=10
- DIAMOND_BARDING=10
- GOLDEN_APPLE(1)=10

# Enables the contraband scanner
ScanContraband: true

# Prohibited items, automatically includes entries in ItemValues
Contraband:
- GOLDEN_APPLE(0)
- POTION

# Enables debugging
# ONLY USE IF YOU KNOW WHAT YOU ARE DOING OR HAVE BEEN ASKED TO DO SO BY A DEVELOPER
Debug: false