# Abba Caving Plugin by lennartVH01

# Game duration in seconds
Duration: 1800

# Max players per game, users with permission AbbaCaving.joinFull can still join
PlayerCap: 10

#Example Game with 10 players
# All: 1
# Top: 
# - 7
# - 2
# If FixPlayerWeight == true then the first player would receive 70% of winnings, second would receive 20% and the remaining 10% is divided among the 8 remaining players
# If FixPlayerWeight == false then the first player would receive 7/(7+2+8*1)=7/17 of total winnings, second would receive 2/17 and every remaining player will get 1/17


# Points awarded for each item at the end of an Abba Match
ItemValues:
- type: IRON_ORE
  Value: 1
- type: REDSTONE_ORE
  Value: 2
- type: GOLD_ORE
  Value: 4
- type: LAPIS_ORE
  Value: 8
- type: DIAMOND_ORE
  Value: 10
- type: EMERALD_ORE
  Value: 10
- type: DIAMOND_BARDING
  Value: 10
- type: GOLDEN_APPLE
  damage: 1
  Value: 10

# Enables the contraband scanner
ScanContraband: true

# Prohibited items, automatically includes entries in ItemValues
Contraband:
- type: GOLDEN_APPLE
  damage: 0
- type: POTION

# Enables debugging
# ONLY USE IF YOU KNOW WHAT YOU ARE DOING OR HAVE BEEN ASKED TO DO SO BY A DEVELOPER
Debug: false