# Abba Caving Plugin by lennartVH01

# Game duration in seconds
GameDuration: 1800

# Countdown in seconds
CountdownTime: 5

# Times in game to notify players of the time left in seconds
# Example: a NotifyTime of 120 will let all players know when there are 2 minutes left
NotifyTimes:
- 900
- 300
- 60

# Max players per game, users with permission AbbaCaving.joinFull can still join
PlayerCap: 1

# Ratio of spoils given per player: 
#   All: Amount to be spread over all participants
#   Pot: Amount to be added to general Pot
#   Top: first n players receive these chunks of total wins


WinRatios:
  All: 0.05
  Pot: 0.05
  Top:
  - 0.6
  - 0.2
  - 0.1



# Points awarded for each item at the end of an Abba Match
ItemValues:
- type: IRON_ORE
  Value: 1
- type: REDSTONE_ORE
  Value: 2
- type: GOLD_ORE
  Value: 4
- type: LAPIS_ORE
  Value: 8
- type: DIAMOND_ORE
  Value: 10
- type: EMERALD_ORE
  Value: 10
- type: DIAMOND_BARDING
  Value: 10
- type: GOLDEN_APPLE
  damage: 1
  Value: 10

# Prohibited items, automatically includes entries in BlockValues
Contraband:
- type: GOLDEN_APPLE
  damage: 0
- type: POTION