name: AbbaCaving
main: me.lennartVH01.Main
version: 0.1
description: Abba Caving Management Plugin
author: lennartVH01
commands:
  abba:
    aliases: [ab, abbacaving]
    description: Abba hub command
    permission: AbbaCaving.basic
    permission-message: You don't have permission to use this command!
permissions:
  AbbaCaving.basic:
    description: Gives access to basic commands
    default: true
  AbbaCaving.admin:
    description: Gives access to admin commands
    default: op
  AbbaCaving.joinFull:
    description: Allows to join full games
    default: op
  AbbaCaving.joinClosed:
    description: Allows to join closed games
    default: op
  AbbaCaving.allowContraband:
    description: Users with this permission will not be scanned for contraband
    default: op