name: AbbaCaving
main: me.lennartVH01.Main
version: 0.1
description: Abba Caving Management Plugin
author: lennartVH01
commands:
  abba:
    aliases: [ab, abbacaving]
    description: Abba hub command
    permission: AbbaCaving.player
    permission-message: You don't have permission to use this command!
  abbaadmin:
    aliases: [aa, abbaa]
    description: Abba Admin Command
    permission: AbbaCaving.admin
    permission-message: You don't have permission to use this command!
permissions:
  AbbaCaving.player:
    description: Gives access to basic commands
    default: true
  AbbaCaving.admin:
    description: Gives access to admin commands
    default: op
  AbbaCaving.joinFull:
    description: Allows to join full games
    default: op
  AbbaCaving.registerChest:
    description: Allows registering of chests to an Abba Game
    default: op
  AbbaCaving.allowContraband:
    description: Users with this permission will not be scanned for contraband
    default: op